### ISSUE TITLE
Affects of latency / speedup 

### ISSUE THREAD

**Issue by shairoz-deci** [DingXiaoH/ResRep#10]
Thank you for sharing this great repo and paper.
I wonder if you examined the affects of ResRep pruning on the latency or throughput of a model?

It is not uncommon that pruning, even at a large scale doesn't yield much improvement on the model's inference speed, was ResRep able to have a profound impact on the inference speed?

Thanks in advanced.

**Comment by DingXiaoH** [comment]
Hi, the actual latency depends on the computing framework and hardware, and it is a common practice to report the FLOPs.
