### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by yongyongdown** [DingXiaoH/ResRep#15]
Hello, I'm a pruning newbie.
Thanks for sharing your great research.

I have a few questions.

- Many open source pruning codes use the public classification dataset. but, I want to pruning a mobilenet based object detection model using a custom dataset. Isn't this a problem for using this ResRep?

- If that's possible, I'd really appreciate it if you could give me an example of how to proceed.

Thank you sincerely.

**Comment by DingXiaoH** [comment]
Hi, I would suggest you use a popular framework (like MMDetection) and customize some code (loss and hooks, in MMDetection).
