### ISSUE TITLE
Should the Compactor‘s conv layer's group = in_channels = out_channels

### ISSUE THREAD

**Issue by RizhaoCai** [DingXiaoH/ResRep#18]
![image](https://user-images.githubusercontent.com/37952703/157202438-cb8aa66a-6bcb-4a23-a9bb-611cf47a0275.png)

Should the parameter `groups=num_features`  in the compactor?

**Comment by DingXiaoH** [comment]
Groups = in_channels = out_channels would create a depthwise conv. But we desire a pointwise (dense 1x1) conv.
