### ISSUE TITLE
Paper Comments from Reviewer Available?

### ISSUE THREAD

**Issue by JUGGHM** [DingXiaoH/ResRep#5]
Hi Xiaohan! This is in the inspiring re-param series and it's a really nice work. And I wonder if it is available to know how the reviewers of model compression community react to this paper?

**Comment by DingXiaoH** [comment]
I don't think I am allowed to make the reviews publicly available... Maybe ICCV will release the reviews on the official website just like NeurIPS...

**Comment by JUGGHM** [comment]
Thanks for your reply!
